### ISSUE TITLE
Backend SQL database requirements

### ISSUE THREAD

**Issue by ptide** [VeeamHub/best-practices-guide#26]
Hi,

Is it really OK that we state in the BP guide things like this one?

"it is highly recommended to update the database server to Microsoft SQL Server (Express) 2014 or higher"

We don't use such wording in the user guide, an I'd assume that we should not do so in BP either. I'm not asking to explicitly define the whole list of supported versions, but at least there should be something like "for a detailed list of supported version please refer to the user guide".

Thanks

**Comment by dellock6** [comment]
Also, by definition the BP guide is NOT the user guide, they both have their place. I don't see why we should note everytime that further information are available in the UG, it's implicit and iirc it's stated at the beginning of the BP guide itself. I don't see contradictions, BP "just" lists what we architects have seen as the best choice among those available.

**Comment by ptide** [comment]
Ok, fair enough, I just wanted to double check. Sorry for bothering you for nothing.

Thanks
